// Generated by https://quicktype.io
export const userbill = "https://utcc-prc.demotoday.net/bt-order-api/api/BtResUserBill"
export interface BtResUserBill {
  IsSuccess: boolean;
  StatusCode: number;
  StatusCodeDecimal: null;
  Message: string;
  StatusDateTime: Date;
  Value: Value[];
}

export interface Value {
  BILL_ID: number;
  USER_ID: number;
  FOOD_ID: number;
  RES_ID: number;
  BILL_RESULT: number;
  RECORD_STATUS: string;
  CREATE_USER_ID: number;
  UPDATE_USER_ID: number;
  USER_STATUS: string;
  CREATE_DATE: Date;
  UPDATE_DATE: Date;
  BILL_NOTE: string;
  BILL_OPTION: string;
}
