
export const foodlisturl = "https://utcc-prc.demotoday.net/bt-order-api/api/BtResFoodList";

// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface BtResFoodList {
  IsSuccess:         boolean;
  StatusCode:        number;
  StatusCodeDecimal: null;
  Message:           string;
  StatusDateTime:    Date;
  Value:             Value[];
}

export interface Value {
  FOOD_ID:        number;
  RES_ID:         number;
  FOOD_NAME:      string;
  FOOD_PRICE:     string;
  FOOD_NORMAL:    string;
  FOOD_SPECIAL:   string;
  FOOD_OPTION:    string;
  FOOD_NOTE:      string;
  RECORD_STATUS:  string;
  CREATE_USER_ID: number;
  UPDATE_USER_ID: number;
  USER_STATUS:    string;
  FOOD_IMAGE:     string;
  CREATE_DATE:    Date;
  UPDATE_DATE:    Date;
}
