// Generated by https://quicktype.io
import { Injectable } from '@angular/core'    

export interface BtResUser {
  IsSuccess:         boolean;
  StatusCode:        number;
  StatusCodeDecimal: null;
  Message:           string;
  StatusDateTime:    Date;
  Value:             Value[];
}

export interface Value {
  USER_ID:         number;
  USER_FIRST_NAME: string;
  USER_LAST_NAME:  string;
  USER_EMAIL:      string;
  USER_PASSWORD:   string;
  RECORD_STATUS:   string;
  CREATE_USER_ID:  number;
  UPDATE_USER_ID:  number;
  CREATE_DATE:     Date;
  UPDATE_DATE:     Date;
}

const countries: string[] = [
  'User','Admin'
];


